spring.application.name=GERegister
spring.output.ansi.enabled=ALWAYS

spring.datasource.url=jdbc:postgresql://localhost:5432/geregister_db
spring.datasource.username=geregister_app
spring.datasource.password=123

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.show_sql=false

jwt.secret=SurelyNobodyWillFindThat12345678901234567890123456789012345678901234567890
jwt.expiration=3600000
jwt.issuer=geregister